services:
  postgres:
    image: postgis/postgis:18-3.6
    container_name: pf-postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=personal_foundry
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - pf-network
  pg-admin:
    image: dpage/pgadmin4
    container_name: pf-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - ./postgres-init/servers.json:/pgadmin4/servers.json
    networks:
      - pf-network
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: pf-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - pf-network
  
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: pf-kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    ports:
      - "9092:9092"
    networks:
      - pf-network
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: qs-kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    depends_on:
      - kafka
    networks:
      - pf-network

  spring-consumer:
    build: ./spring-consumer
    container_name: pf-spring-consumer
    restart: on-failure
    depends_on:
      - postgres
      - kafka
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/personal_foundry
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - pf-network
  
networks:
  pf-network:
    driver: bridge
